Trade offer summary
supermetrolog/crmvue pull request #12
Opened 2023-06-16 14:18 UTC by Haskiro

2023-06-20 16:18 UTC, supermetrolog requested changes

2023-06-20 16:18 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +      <span v-if="valueDetails && typeof valueDetails === 'string'">
Чего-то типа isString нет?

2023-06-20 16:18 UTC, supermetrolog commented on src/components/object/offer-parameters.mixin.ts
> +    formattedParameter(parameter: ICharacterictic): string {
Выглядит так себе. Смысл типизации если там может лежать абсолютно любой тип? Если кривые данные с бака приходят, то лучше я их на бэке поправлю

2023-06-22 15:19 UTC, Haskiro commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +      <span v-if="valueDetails && typeof valueDetails === 'string'">
неа, в нативном js нет

2023-06-22 16:37 UTC, supermetrolog approved these changes

2023-06-22 16:37 UTC, merged