Connect complex page with api
supermetrolog/crmvue pull request #13
Opened 2023-06-20 14:28 UTC by Haskiro

1. поменял роуты на complex
2. изменил размеры шапки комплекса и убрал position: sticky
3. изменил внешний вид карты
4. api функция для получения комплекса с объектами
5. модуль для комплекса  в сторе
6. начал соединять с данными с бэка (вставил данные в шапку, первые 2 столбца в таблице о комплексе)
7. убрал варнинги в консоли

2023-06-20 17:21 UTC, supermetrolog requested changes

2023-06-20 17:21 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +        this.propertyValue !== "есть" &&
Это на бэке лучше на цифры поменять

2023-06-20 17:21 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
Я так понимаю этот компонент это уже какой-то монстр? В каждом пул реквесте вижу здесь изменения. И выглядит он странно с кучей условий.

2023-06-20 17:21 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +      return value === null || value === undefined;
Зачем проверять на андефайнед?

2023-06-20 17:21 UTC, supermetrolog commented on src/components/common/with-unit-type/WithUnitType.vue
> +      type: [Number, Boolean],
Как тип может быть и цифрой и булеан?

2023-06-20 17:21 UTC, supermetrolog commented on src/components/common/with-unit-type/unitType/UnitType.vue
> +      type: [Number, Boolean],
См. Выше

2023-06-20 17:21 UTC, supermetrolog commented on src/components/object/object-header/ObjectHeader.vue
> +        ? this.dateFormatter.locale(this.updateDate * 1000)
Что за магическая 1000?

2023-06-20 17:21 UTC, supermetrolog commented on src/components/object/object-map/ObjectMap.vue
>        type: [String, Number],
Как это может быть строкой?

2023-06-22 15:29 UTC, Haskiro commented
1. Переименовал часть компонентов
2. Добавил BaseEntity и отнаследованный от него ComplexEntity
3. Реализовал интерфейс IComplex
4. Компонент PropertyListItem переписал с слотом
5. Начал переписывать таблицы о комплексе, первые 2 столбца готовы

2023-06-22 16:34 UTC, supermetrolog requested changes

2023-06-22 16:34 UTC, supermetrolog commented on src/entities/complex.entity.ts
> +    return this.setBooleanField(this._heating);
Переименуй это. Геттер возвращает сеттер. Это бред. Сеттер вообще ничего не должен возвращать. Максимум сеттер может возвращать this

2023-06-22 16:34 UTC, supermetrolog commented on src/plugins/index.js
> +export const dateFormatter = {
Зачем? Этот объект является частью плагина форматтер. Плагины подрубаются в объект вью. Так что отсюда просто наружу выкидывать куски объектов не хорошо.

2023-06-22 16:34 UTC, supermetrolog commented on src/store/modules/complex/getters.ts
> +  [ComplexGettersTypes.COMPLEX](state) {
Вот это вот странная штука. Зачем здесь константа? Это же просто метод. Почему его просто не назвать как все другие методы? 
ИДЕ даже не сможет подсказать что такой метод существует из-за того что он в рантайме генерится. 
Во вью можно вызывать геттер или экшен по модульно. То есть можно в компоненте указать из какого модуля стора мы вызываем геттер. 
Ну в общем эта константа это так себе. Не вижу плюсов от ее использования никаких. Только минусы, которые я описал выше

2023-06-23 17:00 UTC, supermetrolog requested changes

2023-06-26 12:46 UTC, Haskiro commented on src/views/ComplexView/ComplexView.vue
> +import ComplexAbout from "@/components/object/complex-about/ComplexAbout.vue";
Веб шторм не помог, ошибка выскакивала. Поменял вручную

2023-06-27 20:14 UTC, supermetrolog requested changes

2023-06-27 20:14 UTC, supermetrolog commented on src/entities/objects.entity.ts
> +		return this._photo ? this._photo.map(link => ({src: "https://pennylane.pro" + link})) : null;
Нельзя хардкодить такие штуки. У нас есть другой резервный сервак где другой домен. Для разруливания доменов есть то ли плагин то ли утилита я уже не помню. 
В будущем на .env файлы перейти надо будет

2023-06-30 18:49 UTC, supermetrolog approved these changes

2023-06-30 18:49 UTC, merged