Offer view page
supermetrolog/crmvue pull request #6
Opened 2023-05-26 13:54 UTC by Haskiro

1. changed existing styles to match the design layout
2. division large components into smaller separate components
3. holding deals preview card
4. holding deals item
5. deal info started: header and building info created, layout of aside block created

2023-05-26 18:01 UTC, supermetrolog requested changes

2023-05-26 18:01 UTC, supermetrolog commented on src/utils/index.js
> +}
Вынести в форматтер плагин

2023-05-26 18:17 UTC, Haskiro commented on src/components/object/object-holdings/deal-info/DealInfo.vue
> +              unitType: 11,
в макете такое было

2023-05-26 18:30 UTC, supermetrolog commented on src/components/object/object-holdings/deal-info/DealInfo.vue
> +              unitType: 11,
Вопрос про 84 строку. unitType это что?

2023-05-29 13:33 UTC, Haskiro commented on package.json
> +        "uuid4": "^2.0.3",
уберу, когда с бэком соединять буду. Щас с помощью него генерил id для соединения input с label, иначе пересекались айдишники.

2023-05-29 13:46 UTC, Haskiro commented on src/components/object/object-holdings/deal-info/DealInfo.vue
> +              unitType: 11,
знак процента. Больше не было идей, как прокидывать, что 80 это именно проценты

2023-05-29 13:49 UTC, Haskiro commented on src/components/object/object-holdings/deal-info/DealInfo.vue
> +  data() {
Зачем так глубоко прокидывать пропсы? Я думал потом просто из  стора их взять

2023-05-29 13:53 UTC, Haskiro commented on src/components/object/object-holdings/deal-info/deal-detailed-info/DealDetailedInfo.vue
> +          list: [
Поэтому очень грустно, что доки нет(

2023-05-29 14:25 UTC, Haskiro commented on src/components/object/object-holdings/deal-info/deal-detailed-info/building-info/BuildingInfo.vue
> +          {{ formatValue(price.sum.value) }}
этот formatValue использует внутри себя formatterObject из плагинов. саму функцию я в utils положил

2023-05-29 14:33 UTC, Haskiro commented on src/components/object/object-holdings/deal-info/deal-info-header/DealInfoHeader.vue
> +      activeFilter: "per_month",
в макете есть переключатели за месяц, за м2/в месяц и за м2/год. На pennylane.pro Такого щас нет

2023-05-29 14:40 UTC, Haskiro commented on src/components/object/object-holdings/deals/deal-item/floors/DealFloors.vue
> +              }"
тут значения используются в цикле

2023-05-29 14:54 UTC, Haskiro commented on src/components/object/object-holdings/deals/deal-item/floors/head/DealFloorHead.vue
> +      id: uuid4(),
чтобы сделать уникальные id. Потом уберу, просто в разные блоках с строениями и участками использовались одни и те же данные и id для input пересекались

2023-05-29 15:09 UTC, Haskiro commented on src/components/object/object-holdings/object-holdings-tabs/ObjectHoldingsTabs.vue
>                v-for="(prop, idx) in holdingsProperties[0]"
Не я делал, но гляну

2023-05-29 15:18 UTC, Haskiro commented on src/components/object/ui/deal-preview/DealPreview.vue
> +        v-html="unitTypesList.get(deal.price.type)"
тут как раз таки html и вставляется, там большая часть единиц с <sup>2</sup>

2023-06-01 02:26 UTC, supermetrolog requested changes

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/DealFloors.vue
> +        case 5:
Брать из констант

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/head/DealFloorHead.vue
> +        <span v-html="UnitTypesList.get(1)" />
Избавиться от прокидывания html

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/head/DealFloorHead.vue
> +      id: uuid4(),
Все-таки сейчас убери. Всё и так должно без рандомных айдишек работать. А то "потом" никогда не наступит)

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/section/DealFloorSection.vue
> +      ???: {{ section.company.join(", ") }}
Компани в ед. числе, но это массив почему-то. И в вычисляемое свойство это

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/section/DealFloorSection.vue
> +      id: uuid4(),
Избавиться

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/section/DealFloorSection.vue
> +        case 3:
Статусы брать из констант

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal.data.json
> +            "label": "% заполняемости объекта",
Лэйблы не будут приходит с бэка 
Можешь в целом пока оставить это, но когда будут приходить данные с бэка придется на фронте маппить данные в нужную тебе структуру. 
А вообще ты можешь подглядывать на  эндпоинты которые существуют. Можешь смотреть в каком виде приходят данные.

2023-06-01 02:26 UTC, supermetrolog commented on src/components/object/ui/deal-preview/DealPreview.vue
> +        success: deal.status === DealStatusType.FOR_RENT,
Вычисляемое свойство. isRent, например

2023-06-01 02:26 UTC, supermetrolog commented on src/const/Const.js
> +]);
Это зачем ты переделал в мапу?
Во первых в js объект это и есть мапа. Во вторых может понадобиться добавить доп свойства, поэтому в виде объекта к ним удобней обращаться. 
Да, все константы сделаны через мапу, но это ошибка. Нужно делать теперь правильно) 
Так что лучше вернуть как было (массив объектов)

2023-06-02 12:08 UTC, Haskiro commented on src/components/object/object-holdings/deals/deal.data.json
> +            "label": "% заполняемости объекта",
На текущий пул реквест так оставлю, буду переделывать

2023-06-02 16:38 UTC, supermetrolog requested changes

2023-06-02 16:38 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +      </span>
Вынести в отдельный компонент. Прокинуть туда юнит как пропс и там уже прописать все эти ифы

2023-06-02 16:38 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +      <span v-if="addRubUnit"> ₽ </span>
А зачем тогда тонна кода с юнит тайп если ты им не пользуешься? Иногда пользуешься а вот в данном случае нет

2023-06-02 16:38 UTC, supermetrolog commented on src/views/ObjectView/ObjectView.vue
> +      ...data,
Так лучше не делать. Когда заходишь в компонент нужно сразу видеть какие данные там есть. Свойства объекта должны быть статичны, а не генериться динамически

2023-06-05 16:32 UTC, supermetrolog requested changes

2023-06-05 16:32 UTC, supermetrolog commented on src/components/object/object-holdings/deals/deal-item/floors/section/DealFloorSection.vue
> +      />
Инпут есть, а формы нет. Это как? И почему не через v-model сделано? 
Если это нормальная форма, вынеси ее в отдельный компонент с суффиксом Form. 
Так же в компонентах есть папочка form, где много чего реализовано. Можешь брать оттуда компоненты формы.

2023-06-05 16:38 UTC, supermetrolog requested changes

2023-06-05 16:38 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +      :additionalUnit="additionalUnit"
Это зачем? Если есть случаи, когда дополнительно указывается вторая единица измерения, то просто вынеси этот случай в отдельную константу и всё. Это можно разрулить без дополнительного пропса.

2023-06-05 16:38 UTC, supermetrolog commented on src/components/common/property-list/property-list-item/PropertyListItem.vue
> +    additionalUnit: {
Разрулить без дополнительного пропса

2023-06-06 16:01 UTC, supermetrolog approved these changes

2023-06-06 16:01 UTC, merged